linters:
  enable-all: true
  disable:
    - gochecknoinits
    - paralleltest
    - wrapcheck
    - gosec
    - gochecknoglobals
    - musttag
    - revive
    - depguard
    - inamedparam
    - stylecheck
    - ireturn
    - forcetypeassert
    - varnamelen
    - err113
    - nlreturn
    - wsl
    - exhaustruct

    # Deprecated ones:
    - execinquery
    - gomnd
    - structcheck
    - interfacer
    - deadcode
    - varcheck
    - ifshort
    - exhaustivestruct
    - golint
    - maligned
    - nosnakecase
    - scopelint

linters-settings:
  gocyclo:
    min-complexity: 15

  cyclop:
    max-complexity: 12

  gomoddirectives:
    replace-allow-list:
      - github.com/bradleyjkemp/grpc-tools

issues:
  exclude-use-default: false
  exclude-dirs-use-default: false
