linters:
  enable-all: true
  disable:
    - gochecknoinits
    - paralleltest
    - wrapcheck
    - gosec
    - gochecknoglobals
    - musttag
    - revive
    - depguard
    - inamedparam
    - stylecheck
    - ireturn
    - forcetypeassert
    - varnamelen
    - goerr113
    - nlreturn
    - wsl
    - exhaustruct

    # Deprecated ones:
    - structcheck
    - interfacer
    - deadcode
    - varcheck
    - ifshort
    - exhaustivestruct
    - golint
    - maligned
    - nosnakecase
    - scopelint

linters-settings:
  gocyclo:
    min-complexity: 15

issues:
  exclude-use-default: false
  exclude-dirs-use-default: false
