name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - uses: actions/checkout@v4

      - name: lint
        run: go run github.com/ysmood/golangci-lint@latest

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0

      - name: test
        run: go test ./...
